# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: 'Terraform Module Variables'

steps:
- task: Go@0
  displayName: 'Go get golint'
  inputs:
    command: 'get'
    arguments: '-u golang.org/x/lint/golint'

- task: Go@0
  displayName: 'Go get terratest'
  inputs:
    command: 'get'
    arguments: 'github.com/gruntwork-io/terratest/modules/terraform'

- task: Go@0
  displayName: 'Go get testify/assert'
  inputs:
    command: 'get'
    arguments: 'github.com/stretchr/testify/assert'

- task: Go@0
  displayName: 'Go test'
  inputs:
    command: 'test'
    arguments: './test'
  env:
    ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)

- task: Npm@1
  displayName: 'Npm Install'
  inputs:
    command: 'install'

- task: Bash@3
  displayName: 'Release via semantic-release'
  inputs:
    targetType: 'inline'
    script: 'npx semantic-release'
  env:
    GH_TOKEN: $(GH_TOKEN)